"""
Real Players Database Generator
Creates a database of real cricket players from Test nations and Tier 2 associates
Based on current international squads (2024-2025)
"""

import json
import random

# Real player data - Test Nations (12 teams)
REAL_PLAYERS = {
    "India": [
        # Batters
        {"name": "Rohit Sharma", "age": 37, "role": "Opening Batter", "batting": 91, "bowling": 25, "fielding": 82},
        {"name": "Virat Kohli", "age": 35, "role": "Top Order Batter", "batting": 92, "bowling": 22, "fielding": 88},
        {"name": "Shubman Gill", "age": 24, "role": "Opening Batter", "batting": 86, "bowling": 28, "fielding": 85},
        {"name": "Yashasvi Jaiswal", "age": 22, "role": "Opening Batter", "batting": 84, "bowling": 20, "fielding": 83},
        {"name": "KL Rahul", "age": 32, "role": "Middle Order Batter", "batting": 85, "bowling": 24, "fielding": 84},
        {"name": "Shreyas Iyer", "age": 29, "role": "Middle Order Batter", "batting": 82, "bowling": 30, "fielding": 81},
        {"name": "Rishabh Pant", "age": 26, "role": "Wicketkeeper Batter", "batting": 87, "bowling": 20, "fielding": 86},
        # All-rounders
        {"name": "Ravindra Jadeja", "age": 35, "role": "Genuine Allrounder (Finger Spin)", "batting": 78, "bowling": 85, "fielding": 92},
        {"name": "Hardik Pandya", "age": 30, "role": "Batting Allrounder (Fast Medium)", "batting": 80, "bowling": 82, "fielding": 87},
        {"name": "Axar Patel", "age": 30, "role": "Bowling Allrounder (Finger Spin)", "batting": 72, "bowling": 83, "fielding": 80},
        # Bowlers
        {"name": "Jasprit Bumrah", "age": 30, "role": "Fast Bowler", "batting": 35, "bowling": 95, "fielding": 78},
        {"name": "Mohammed Siraj", "age": 30, "role": "Fast Bowler", "batting": 38, "bowling": 86, "fielding": 76},
        {"name": "Mohammed Shami", "age": 33, "role": "Fast Bowler", "batting": 40, "bowling": 88, "fielding": 74},
        {"name": "Kuldeep Yadav", "age": 29, "role": "Wrist Spinner", "batting": 42, "bowling": 84, "fielding": 75},
        {"name": "Ravichandran Ashwin", "age": 37, "role": "Off Spinner", "batting": 68, "bowling": 89, "fielding": 77},
    ],
    
    "Australia": [
        # Batters
        {"name": "Steve Smith", "age": 34, "role": "Top Order Batter", "batting": 90, "bowling": 28, "fielding": 84},
        {"name": "Marnus Labuschagne", "age": 29, "role": "Top Order Batter", "batting": 88, "bowling": 45, "fielding": 82},
        {"name": "David Warner", "age": 37, "role": "Opening Batter", "batting": 89, "bowling": 22, "fielding": 80},
        {"name": "Travis Head", "age": 30, "role": "Opening Batter", "batting": 85, "bowling": 35, "fielding": 83},
        {"name": "Usman Khawaja", "age": 37, "role": "Opening Batter", "batting": 86, "bowling": 20, "fielding": 78},
        {"name": "Cameron Green", "age": 24, "role": "Batting Allrounder (Fast Medium)", "batting": 80, "bowling": 81, "fielding": 86},
        {"name": "Alex Carey", "age": 32, "role": "Wicketkeeper Batter", "batting": 78, "bowling": 20, "fielding": 85},
        # All-rounders
        {"name": "Mitchell Marsh", "age": 32, "role": "Batting Allrounder (Fast Medium)", "batting": 79, "bowling": 80, "fielding": 82},
        {"name": "Glenn Maxwell", "age": 35, "role": "Batting Allrounder (Wrist Spin)", "batting": 82, "bowling": 76, "fielding": 88},
        # Bowlers
        {"name": "Pat Cummins", "age": 30, "role": "Fast Bowler", "batting": 55, "bowling": 92, "fielding": 81},
        {"name": "Mitchell Starc", "age": 34, "role": "Fast Bowler", "batting": 48, "bowling": 90, "fielding": 79},
        {"name": "Josh Hazlewood", "age": 33, "role": "Fast Bowler", "batting": 42, "bowling": 89, "fielding": 77},
        {"name": "Nathan Lyon", "age": 36, "role": "Off Spinner", "batting": 50, "bowling": 87, "fielding": 76},
        {"name": "Adam Zampa", "age": 31, "role": "Wrist Spinner", "batting": 38, "bowling": 83, "fielding": 74},
    ],
    
    "England": [
        # Batters
        {"name": "Joe Root", "age": 33, "role": "Top Order Batter", "batting": 91, "bowling": 42, "fielding": 85},
        {"name": "Ben Stokes", "age": 33, "role": "Genuine Allrounder (Fast Medium)", "batting": 84, "bowling": 82, "fielding": 89},
        {"name": "Harry Brook", "age": 24, "role": "Middle Order Batter", "batting": 85, "bowling": 25, "fielding": 83},
        {"name": "Jonny Bairstow", "age": 34, "role": "Wicketkeeper Batter", "batting": 83, "bowling": 22, "fielding": 84},
        {"name": "Jos Buttler", "age": 33, "role": "Wicketkeeper Batter", "batting": 85, "bowling": 20, "fielding": 86},
        {"name": "Zak Crawley", "age": 26, "role": "Opening Batter", "batting": 80, "bowling": 24, "fielding": 81},
        {"name": "Ben Duckett", "age": 29, "role": "Opening Batter", "batting": 82, "bowling": 20, "fielding": 80},
        # All-rounders
        {"name": "Moeen Ali", "age": 36, "role": "Batting Allrounder (Finger Spin)", "batting": 76, "bowling": 80, "fielding": 79},
        {"name": "Chris Woakes", "age": 35, "role": "Bowling Allrounder (Fast Medium)", "batting": 65, "bowling": 84, "fielding": 80},
        {"name": "Sam Curran", "age": 25, "role": "Bowling Allrounder (Fast Medium)", "batting": 68, "bowling": 81, "fielding": 82},
        # Bowlers
        {"name": "James Anderson", "age": 41, "role": "Fast Medium Pacer", "batting": 35, "bowling": 88, "fielding": 72},
        {"name": "Stuart Broad", "age": 37, "role": "Fast Medium Pacer", "batting": 40, "bowling": 87, "fielding": 74},
        {"name": "Mark Wood", "age": 34, "role": "Fast Bowler", "batting": 38, "bowling": 86, "fielding": 76},
        {"name": "Jofra Archer", "age": 29, "role": "Fast Bowler", "batting": 42, "bowling": 88, "fielding": 78},
        {"name": "Adil Rashid", "age": 36, "role": "Wrist Spinner", "batting": 45, "bowling": 84, "fielding": 75},
    ],
    
    "Pakistan": [
        {"name": "Babar Azam", "age": 29, "role": "Top Order Batter", "batting": 89, "bowling": 28, "fielding": 84},
        {"name": "Mohammad Rizwan", "age": 31, "role": "Wicketkeeper Batter", "batting": 84, "bowling": 22, "fielding": 85},
        {"name": "Fakhar Zaman", "age": 33, "role": "Opening Batter", "batting": 82, "bowling": 25, "fielding": 80},
        {"name": "Imam-ul-Haq", "age": 28, "role": "Opening Batter", "batting": 80, "bowling": 20, "fielding": 78},
        {"name": "Shadab Khan", "age": 25, "role": "Bowling Allrounder (Wrist Spin)", "batting": 68, "bowling": 82, "fielding": 84},
        {"name": "Shaheen Afridi", "age": 24, "role": "Fast Bowler", "batting": 40, "bowling": 90, "fielding": 79},
        {"name": "Haris Rauf", "age": 30, "role": "Fast Bowler", "batting": 35, "bowling": 86, "fielding": 76},
        {"name": "Naseem Shah", "age": 21, "role": "Fast Bowler", "batting": 38, "bowling": 84, "fielding": 77},
        {"name": "Mohammad Nawaz", "age": 30, "role": "Bowling Allrounder (Finger Spin)", "batting": 65, "bowling": 79, "fielding": 78},
        {"name": "Hasan Ali", "age": 29, "role": "Fast Bowler", "batting": 42, "bowling": 82, "fielding": 75},
        {"name": "Iftikhar Ahmed", "age": 33, "role": "Batting Allrounder (Finger Spin)", "batting": 75, "bowling": 72, "fielding": 79},
        {"name": "Agha Salman", "age": 30, "role": "Batting Allrounder (Finger Spin)", "batting": 74, "bowling": 70, "fielding": 77},
        {"name": "Usama Mir", "age": 28, "role": "Wrist Spinner", "batting": 40, "bowling": 78, "fielding": 73},
        {"name": "Abrar Ahmed", "age": 25, "role": "Wrist Spinner", "batting": 38, "bowling": 80, "fielding": 72},
        {"name": "Sarfaraz Ahmed", "age": 37, "role": "Wicketkeeper Batter", "batting": 76, "bowling": 20, "fielding": 80},
    ],
    
    "South Africa": [
        {"name": "Temba Bavuma", "age": 33, "role": "Top Order Batter", "batting": 80, "bowling": 25, "fielding": 83},
        {"name": "Quinton de Kock", "age": 31, "role": "Wicketkeeper Batter", "batting": 87, "bowling": 20, "fielding": 85},
        {"name": "Aiden Markram", "age": 29, "role": "Top Order Batter", "batting": 84, "bowling": 48, "fielding": 84},
        {"name": "Rassie van der Dussen", "age": 35, "role": "Middle Order Batter", "batting": 82, "bowling": 35, "fielding": 81},
        {"name": "David Miller", "age": 34, "role": "Middle Order Batter", "batting": 83, "bowling": 28, "fielding": 86},
        {"name": "Heinrich Klaasen", "age": 32, "role": "Wicketkeeper Batter", "batting": 81, "bowling": 22, "fielding": 82},
        {"name": "Marco Jansen", "age": 24, "role": "Bowling Allrounder (Fast Medium)", "batting": 65, "bowling": 84, "fielding": 80},
        {"name": "Kagiso Rabada", "age": 29, "role": "Fast Bowler", "batting": 42, "bowling": 91, "fielding": 79},
        {"name": "Anrich Nortje", "age": 30, "role": "Fast Bowler", "batting": 38, "bowling": 88, "fielding": 77},
        {"name": "Lungi Ngidi", "age": 28, "role": "Fast Bowler", "batting": 40, "bowling": 85, "fielding": 76},
        {"name": "Keshav Maharaj", "age": 34, "role": "Off Spinner", "batting": 52, "bowling": 83, "fielding": 75},
        {"name": "Tabraiz Shamsi", "age": 34, "role": "Wrist Spinner", "batting": 38, "bowling": 82, "fielding": 73},
        {"name": "Gerald Coetzee", "age": 23, "role": "Fast Bowler", "batting": 36, "bowling": 82, "fielding": 78},
        {"name": "Tristan Stubbs", "age": 23, "role": "Middle Order Batter", "batting": 78, "bowling": 30, "fielding": 84},
        {"name": "Reeza Hendricks", "age": 34, "role": "Opening Batter", "batting": 79, "bowling": 24, "fielding": 80},
    ],
    
    "New Zealand": [
        {"name": "Kane Williamson", "age": 33, "role": "Top Order Batter", "batting": 90, "bowling": 32, "fielding": 86},
        {"name": "Tom Latham", "age": 32, "role": "Opening Batter", "batting": 84, "bowling": 24, "fielding": 83},
        {"name": "Devon Conway", "age": 32, "role": "Opening Batter", "batting": 85, "bowling": 20, "fielding": 82},
        {"name": "Daryl Mitchell", "age": 32, "role": "Batting Allrounder (Fast Medium)", "batting": 82, "bowling": 75, "fielding": 84},
        {"name": "Glenn Phillips", "age": 27, "role": "Batting Allrounder (Wrist Spin)", "batting": 80, "bowling": 72, "fielding": 87},
        {"name": "Rachin Ravindra", "age": 24, "role": "Batting Allrounder (Wrist Spin)", "batting": 81, "bowling": 74, "fielding": 83},
        {"name": "Mitchell Santner", "age": 32, "role": "Bowling Allrounder (Finger Spin)", "batting": 68, "bowling": 81, "fielding": 85},
        {"name": "Tim Southee", "age": 35, "role": "Fast Medium Pacer", "batting": 48, "bowling": 86, "fielding": 76},
        {"name": "Trent Boult", "age": 34, "role": "Fast Medium Pacer", "batting": 42, "bowling": 88, "fielding": 78},
        {"name": "Matt Henry", "age": 32, "role": "Fast Medium Pacer", "batting": 40, "bowling": 84, "fielding": 75},
        {"name": "Lockie Ferguson", "age": 33, "role": "Fast Bowler", "batting": 38, "bowling": 86, "fielding": 77},
        {"name": "Ish Sodhi", "age": 31, "role": "Wrist Spinner", "batting": 42, "bowling": 80, "fielding": 74},
        {"name": "Tom Blundell", "age": 33, "role": "Wicketkeeper Batter", "batting": 78, "bowling": 20, "fielding": 81},
        {"name": "Will Young", "age": 31, "role": "Top Order Batter", "batting": 79, "bowling": 28, "fielding": 80},
        {"name": "Mark Chapman", "age": 30, "role": "Middle Order Batter", "batting": 77, "bowling": 35, "fielding": 82},
    ],
    
    "West Indies": [
        {"name": "Shai Hope", "age": 30, "role": "Wicketkeeper Batter", "batting": 82, "bowling": 22, "fielding": 84},
        {"name": "Nicholas Pooran", "age": 28, "role": "Wicketkeeper Batter", "batting": 84, "bowling": 20, "fielding": 86},
        {"name": "Brandon King", "age": 29, "role": "Opening Batter", "batting": 79, "bowling": 25, "fielding": 81},
        {"name": "Kyle Mayers", "age": 31, "role": "Batting Allrounder (Fast Medium)", "batting": 78, "bowling": 76, "fielding": 82},
        {"name": "Rovman Powell", "age": 30, "role": "Batting Allrounder (Fast)", "batting": 77, "bowling": 70, "fielding": 84},
        {"name": "Jason Holder", "age": 32, "role": "Genuine Allrounder (Fast Medium)", "batting": 74, "bowling": 83, "fielding": 85},
        {"name": "Alzarri Joseph", "age": 27, "role": "Fast Bowler", "batting": 40, "bowling": 85, "fielding": 78},
        {"name": "Romario Shepherd", "age": 29, "role": "Bowling Allrounder (Fast Medium)", "batting": 65, "bowling": 79, "fielding": 80},
        {"name": "Akeal Hosein", "age": 30, "role": "Off Spinner", "batting": 45, "bowling": 81, "fielding": 76},
        {"name": "Gudakesh Motie", "age": 29, "role": "Off Spinner", "batting": 42, "bowling": 79, "fielding": 74},
        {"name": "Shamar Joseph", "age": 24, "role": "Fast Bowler", "batting": 35, "bowling": 82, "fielding": 77},
        {"name": "Kemar Roach", "age": 36, "role": "Fast Bowler", "batting": 38, "bowling": 84, "fielding": 73},
        {"name": "Shimron Hetmyer", "age": 27, "role": "Middle Order Batter", "batting": 80, "bowling": 28, "fielding": 83},
        {"name": "Alick Athanaze", "age": 24, "role": "Top Order Batter", "batting": 76, "bowling": 30, "fielding": 79},
        {"name": "Joshua Da Silva", "age": 25, "role": "Wicketkeeper Batter", "batting": 75, "bowling": 20, "fielding": 80},
    ],
    
    "Sri Lanka": [
        {"name": "Kusal Mendis", "age": 29, "role": "Wicketkeeper Batter", "batting": 83, "bowling": 22, "fielding": 84},
        {"name": "Pathum Nissanka", "age": 26, "role": "Opening Batter", "batting": 81, "bowling": 24, "fielding": 82},
        {"name": "Charith Asalanka", "age": 26, "role": "Middle Order Batter", "batting": 79, "bowling": 45, "fielding": 81},
        {"name": "Sadeera Samarawickrama", "age": 28, "role": "Middle Order Batter", "batting": 77, "bowling": 30, "fielding": 80},
        {"name": "Wanindu Hasaranga", "age": 26, "role": "Bowling Allrounder (Wrist Spin)", "batting": 68, "bowling": 86, "fielding": 83},
        {"name": "Dhananjaya de Silva", "age": 32, "role": "Batting Allrounder (Wrist Spin)", "batting": 80, "bowling": 78, "fielding": 82},
        {"name": "Angelo Mathews", "age": 37, "role": "Batting Allrounder (Fast Medium)", "batting": 82, "bowling": 74, "fielding": 79},
        {"name": "Dasun Shanaka", "age": 32, "role": "Bowling Allrounder (Fast Medium)", "batting": 72, "bowling": 76, "fielding": 81},
        {"name": "Maheesh Theekshana", "age": 24, "role": "Off Spinner", "batting": 40, "bowling": 83, "fielding": 76},
        {"name": "Matheesha Pathirana", "age": 21, "role": "Fast Bowler", "batting": 32, "bowling": 84, "fielding": 78},
        {"name": "Dilshan Madushanka", "age": 23, "role": "Fast Bowler", "batting": 35, "bowling": 82, "fielding": 77},
        {"name": "Lahiru Kumara", "age": 27, "role": "Fast Bowler", "batting": 38, "bowling": 83, "fielding": 75},
        {"name": "Dunith Wellalage", "age": 21, "role": "Off Spinner", "batting": 50, "bowling": 79, "fielding": 76},
        {"name": "Kusal Perera", "age": 34, "role": "Wicketkeeper Batter", "batting": 80, "bowling": 20, "fielding": 82},
        {"name": "Dimuth Karunaratne", "age": 36, "role": "Opening Batter", "batting": 81, "bowling": 25, "fielding": 78},
    ],
    
    "Bangladesh": [
        {"name": "Shakib Al Hasan", "age": 37, "role": "Genuine Allrounder (Finger Spin)", "batting": 82, "bowling": 85, "fielding": 83},
        {"name": "Mushfiqur Rahim", "age": 37, "role": "Wicketkeeper Batter", "batting": 83, "bowling": 20, "fielding": 84},
        {"name": "Litton Das", "age": 29, "role": "Wicketkeeper Batter", "batting": 80, "bowling": 22, "fielding": 83},
        {"name": "Najmul Hossain Shanto", "age": 25, "role": "Top Order Batter", "batting": 79, "bowling": 30, "fielding": 81},
        {"name": "Towhid Hridoy", "age": 23, "role": "Middle Order Batter", "batting": 76, "bowling": 32, "fielding": 80},
        {"name": "Mehidy Hasan Miraz", "age": 26, "role": "Bowling Allrounder (Finger Spin)", "batting": 70, "bowling": 81, "fielding": 79},
        {"name": "Mahmudullah", "age": 38, "role": "Batting Allrounder (Finger Spin)", "batting": 78, "bowling": 72, "fielding": 77},
        {"name": "Mustafizur Rahman", "age": 28, "role": "Fast Bowler", "batting": 35, "bowling": 84, "fielding": 76},
        {"name": "Taskin Ahmed", "age": 29, "role": "Fast Bowler", "batting": 38, "bowling": 82, "fielding": 77},
        {"name": "Shoriful Islam", "age": 23, "role": "Fast Bowler", "batting": 32, "bowling": 80, "fielding": 78},
        {"name": "Hasan Mahmud", "age": 24, "role": "Fast Bowler", "batting": 34, "bowling": 79, "fielding": 76},
        {"name": "Nasum Ahmed", "age": 29, "role": "Off Spinner", "batting": 42, "bowling": 78, "fielding": 74},
        {"name": "Taijul Islam", "age": 32, "role": "Off Spinner", "batting": 40, "bowling": 80, "fielding": 73},
        {"name": "Tanzid Hasan", "age": 23, "role": "Opening Batter", "batting": 75, "bowling": 25, "fielding": 79},
        {"name": "Soumya Sarkar", "age": 31, "role": "Batting Allrounder (Fast Medium)", "batting": 76, "bowling": 68, "fielding": 80},
    ],
    
    "Afghanistan": [
        {"name": "Rashid Khan", "age": 25, "role": "Bowling Allrounder (Wrist Spin)", "batting": 65, "bowling": 92, "fielding": 85},
        {"name": "Mohammad Nabi", "age": 39, "role": "Genuine Allrounder (Finger Spin)", "batting": 78, "bowling": 82, "fielding": 81},
        {"name": "Rahmanullah Gurbaz", "age": 22, "role": "Wicketkeeper Batter", "batting": 82, "bowling": 20, "fielding": 84},
        {"name": "Ibrahim Zadran", "age": 22, "role": "Opening Batter", "batting": 80, "bowling": 25, "fielding": 82},
        {"name": "Azmatullah Omarzai", "age": 24, "role": "Bowling Allrounder (Fast Medium)", "batting": 72, "bowling": 80, "fielding": 83},
        {"name": "Gulbadin Naib", "age": 33, "role": "Bowling Allrounder (Fast Medium)", "batting": 70, "bowling": 76, "fielding": 79},
        {"name": "Naveen-ul-Haq", "age": 25, "role": "Fast Bowler", "batting": 38, "bowling": 83, "fielding": 78},
        {"name": "Fazalhaq Farooqi", "age": 24, "role": "Fast Bowler", "batting": 32, "bowling": 84, "fielding": 79},
        {"name": "Mujeeb Ur Rahman", "age": 23, "role": "Off Spinner", "batting": 40, "bowling": 85, "fielding": 76},
        {"name": "Noor Ahmad", "age": 19, "role": "Wrist Spinner", "batting": 35, "bowling": 81, "fielding": 77},
        {"name": "Hashmatullah Shahidi", "age": 29, "role": "Top Order Batter", "batting": 77, "bowling": 28, "fielding": 78},
        {"name": "Najibullah Zadran", "age": 31, "role": "Middle Order Batter", "batting": 76, "bowling": 30, "fielding": 80},
        {"name": "Ikram Alikhil", "age": 23, "role": "Wicketkeeper Batter", "batting": 74, "bowling": 20, "fielding": 81},
        {"name": "Rahmat Shah", "age": 31, "role": "Top Order Batter", "batting": 78, "bowling": 26, "fielding": 77},
        {"name": "Fareed Ahmad", "age": 24, "role": "Fast Bowler", "batting": 36, "bowling": 79, "fielding": 76},
    ],
    
    "Ireland": [
        {"name": "Paul Stirling", "age": 33, "role": "Opening Batter", "batting": 81, "bowling": 42, "fielding": 80},
        {"name": "Andy Balbirnie", "age": 33, "role": "Top Order Batter", "batting": 78, "bowling": 30, "fielding": 79},
        {"name": "Harry Tector", "age": 24, "role": "Middle Order Batter", "batting": 80, "bowling": 35, "fielding": 82},
        {"name": "Lorcan Tucker", "age": 27, "role": "Wicketkeeper Batter", "batting": 76, "bowling": 20, "fielding": 83},
        {"name": "Curtis Campher", "age": 25, "role": "Bowling Allrounder (Fast Medium)", "batting": 72, "bowling": 78, "fielding": 81},
        {"name": "George Dockrell", "age": 32, "role": "Bowling Allrounder (Finger Spin)", "batting": 68, "bowling": 79, "fielding": 78},
        {"name": "Mark Adair", "age": 28, "role": "Bowling Allrounder (Fast Medium)", "batting": 65, "bowling": 81, "fielding": 80},
        {"name": "Josh Little", "age": 24, "role": "Fast Bowler", "batting": 35, "bowling": 82, "fielding": 77},
        {"name": "Craig Young", "age": 33, "role": "Fast Bowler", "batting": 38, "bowling": 79, "fielding": 75},
        {"name": "Barry McCarthy", "age": 32, "role": "Fast Bowler", "batting": 40, "bowling": 78, "fielding": 76},
        {"name": "Gareth Delany", "age": 27, "role": "Batting Allrounder (Wrist Spin)", "batting": 74, "bowling": 72, "fielding": 82},
        {"name": "Andy McBrine", "age": 31, "role": "Bowling Allrounder (Finger Spin)", "batting": 66, "bowling": 76, "fielding": 77},
        {"name": "Graham Hume", "age": 26, "role": "Fast Bowler", "batting": 36, "bowling": 77, "fielding": 78},
        {"name": "Stephen Doheny", "age": 25, "role": "Wicketkeeper Batter", "batting": 73, "bowling": 20, "fielding": 80},
        {"name": "Ross Adair", "age": 27, "role": "Opening Batter", "batting": 75, "bowling": 28, "fielding": 79},
    ],

    "Zimbabwe": [
        {"name": "Sikandar Raza", "age": 38, "role": "Genuine Allrounder (Finger Spin)", "batting": 80, "bowling": 80, "fielding": 82},
        {"name": "Sean Williams", "age": 37, "role": "Batting Allrounder (Finger Spin)", "batting": 78, "bowling": 76, "fielding": 79},
        {"name": "Craig Ervine", "age": 38, "role": "Top Order Batter", "batting": 77, "bowling": 30, "fielding": 78},
        {"name": "Regis Chakabva", "age": 36, "role": "Wicketkeeper Batter", "batting": 75, "bowling": 20, "fielding": 80},
        {"name": "Blessing Muzarabani", "age": 27, "role": "Fast Bowler", "batting": 38, "bowling": 81, "fielding": 77},
        {"name": "Richard Ngarava", "age": 26, "role": "Fast Bowler", "batting": 36, "bowling": 79, "fielding": 78},
        {"name": "Tendai Chatara", "age": 32, "role": "Fast Bowler", "batting": 40, "bowling": 78, "fielding": 75},
        {"name": "Wellington Masakadza", "age": 31, "role": "Off Spinner", "batting": 50, "bowling": 77, "fielding": 76},
        {"name": "Ryan Burl", "age": 30, "role": "Batting Allrounder (Wrist Spin)", "batting": 72, "bowling": 74, "fielding": 80},
        {"name": "Wessly Madhevere", "age": 23, "role": "Middle Order Batter", "batting": 74, "bowling": 45, "fielding": 81},
        {"name": "Joylord Gumbie", "age": 24, "role": "Wicketkeeper Batter", "batting": 73, "bowling": 20, "fielding": 82},
        {"name": "Innocent Kaia", "age": 24, "role": "Opening Batter", "batting": 72, "bowling": 25, "fielding": 79},
        {"name": "Clive Madande", "age": 23, "role": "Wicketkeeper Batter", "batting": 71, "bowling": 20, "fielding": 80},
        {"name": "Luke Jongwe", "age": 28, "role": "Bowling Allrounder (Fast Medium)", "batting": 65, "bowling": 76, "fielding": 79},
        {"name": "Brandon Mavuta", "age": 26, "role": "Wrist Spinner", "batting": 42, "bowling": 75, "fielding": 74},
    ],
}

